# see https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 20
    commit-message:
      prefix: 'chore(deps): '
      prefix-development: 'chore(deps-dev): '

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    target-branch: main
    assignees: [cicdbot]
    commit-message:
      prefix: 'ci: '
