name = "Ed"
license = "MIT"
licenselink = "https://github.com/sergeyklay/gohugo-theme-ed/blob/master/LICENSE"
description = "Ed theme for minimal editions, based on Alex Gil theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/sergeyklay/gohugo-theme-ed/"

# If you have a running demo of the theme.
demosite = "https://gohugo-theme-ed.netlify.app/"

tags = [
  "blog",
  "clean",
  "customizable",
  "ed",
  "light",
  "minimal",
  "minimalist",
  "multilingual",
  "responsive",
  "search",
  "simple"
]

# The theme's features:
features = [
  "blog",
  "clean",
  "contact form",
  "favicon",
  "jsonfeed",
  "minimal",
  "minimalist",
  "mobile",
  "multilingual",
  "opengraph",
  "posts",
  "responsive",
  "rss",
  "search",
  "shortcodes",
  "simple"
]

min_version = "0.95.0"

# If the theme has a single author.
[author]
  name = "Serghei Iakovlev"
  homepage = "https://serghei.blog/"

# If porting an existing theme.
[original]
  author = "Alex Gil"
  homepage = "https://www.elotroalex.com/"
  repo = "https://github.com/minicomp/ed/"
